name: examine
on:
  workflow_dispatch:
jobs:
  examine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         for pkg in `ls -AF pkgbuild |grep '/$' | tr -d '/'`
         do
         pkgver=$(cat pkgbuild/${pkg}/PKGBUILD|grep pkgver=|awk -F\= '{print $2}')
         pkgonlinever=$(curl https://api.github.com/repos/$(cat pkgbuild/${pkg}/PKGBUILD|grep source=|awk -F\/ '{print $4}')/$(cat pkgbuild/${pkg}/PKGBUILD|grep source=|awk -F\/ '{print $5}')/releases/latest|grep tag_name|awk -F\" '{print $4}')
         if [ ${pkgver} != ${pkgonlinever} ]; then
         sed -i '/pkgver=/cpkgver='"${pkgonlinever}" pkgbuild/${pkg}/PKGBUILD
         echo "$pkg" >> need-update
         fi
         done
         git config --local user.email "w1301511091@hotmail.com"
         git config --local user.name "oganesson0512"
         git add .
         git commit -m "Build" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: Validate PKGBUILD
        id: validate-pkgbuild
        uses: oganesson0512/arch-pkgbuild-builder@v1.16-cle-pre9
        with:
           target: 'pkgbuild'
           dictionary: 'pkgbuild'
