name: examine
on:
  workflow_dispatch:
jobs:
  examine:
    runs_on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - run: |
         for pkg in `ls -AF pkgbuild |grep '/$' | tr -d '/'`
         do
         pkgver=$(cat pkgbuild/${pkg}/PKGBUILD|grep pkgver=|awk -F\= '{print $2}')
         done
